//  A U T H
export const USER_DETAILS = 'USER_DETAILS';
export const USER_TYPE = 'USER_TYPE';
export const AUDITOR_ID = 'AUDITOR_ID';
export const MERCHANT_ID = 'MERCHANT_ID';

// A U D I T O R S
export const ALL_AUDITORS = 'ALL_AUDITORS';
export const ONE_AUDITOR = 'ONE_AUDITOR';
export const AUDITOR_MERCHANTS = 'AUDITOR_MERCHANTS';
export const MERCHANT_POLICIES = 'MERCHANT_POLICIES';
export const POLICIES_LENGTH = 'POLICIES_LENGTH';
export const APPROVED_POLICIES = 'APPROVED_POLICIES';
export const MERCHANT_EVIDENCES = 'MERCHANT_EVIDENCES';
export const EVIDENCES_LENGTH = 'EVIDENCES_LENGTH';
export const APPROVED_EVIDENCES = 'APPROVED_EVIDENCES';
export const MERCHANT_PENTESTS = 'MERCHANT_PENTESTS';
export const MERCHANT_ASVSCANS = 'MERCHANT_ASVSCANS';

// M E R C H A N T S
export const TOTAL_MONTHLY_TRANSACTIONS = 'TOTAL_TRANSACTIONS';
export const DASHBOARD_CARDS = 'DASHBOARD_CARDS';
export const MERCHANT_USERS = 'MERCHANT_USERS';
export const ALL_AUDITS = 'ALL_AUDITS';
export const AUDIT_PAGINATION = 'AUDIT_PAGINATION';
export const POLICIES = 'POLICIES';
export const TOTAL_POLICIES = 'TOTAL_POLICIES';
export const APPR_POLICIES = 'APPR_POLICIES';
export const EVIDENCES = 'EVIDENCE';
export const TOTAL_EVIDENCES = 'TOTAL_EVIDENCES';
export const APPR_EVIDENCES = 'APPR_EVIDENCES';
export const DEFAULT_POLICIES = 'DEFAULT_POLICIES';
export const DEFAULT_EVIDENCES = 'DEFAULT_EVIDENCES';
export const ONE_POLICY = 'ONE_POLICY';
export const ONE_EVIDENCE = 'ONE_EVIDENCE';
export const POLICY_VERSIONS = 'POLICY_VERSIONS';
export const EVIDENCE_VERSIONS = 'EVIDENCE_VERSIONS';
export const PENTESTS = 'PENTESTS';
export const ASVSCANS = 'ASVSCANS';
export const ONE_PENTEST = 'ONE_PENTEST';
export const ONE_ASVSCAN = 'ONE_ASVSCAN';
export const MERCHANT_PROFILE = 'MERCHANT_PROFILE';
export const MERCHANT_SUBDOMAIN = 'MERCHANT_SUBDOMAIN';

// P A Y M E N T
export const ALL_TRANSACTIONS = 'ALL_TRANSACTIONS';
export const ALL_CUSTOMERS = 'ALL_CUSTOMERS';
export const CUSTOMER_PAGINATION = 'CUSTOMER_PAGINATION';
export const SUCCESSFUL_TRANSACTIONS = 'SUCCESSFUL_TRANSACTIONS';
export const AVAILABLE_PROCESSORS = 'AVAILABLE_PROCESSORS';
export const PAYMENT_MERCHANT = 'PAYMENT_MERCHANT';
